# -*- coding: utf-8 -*-
"""optimization code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhpgxAz-FssqRO4uv8UcVrIMN94URc8j
"""

import pandas as pd

# Load the Excel file into a pandas DataFrame
df = pd.read_excel('/content/Transportation and Logistics Tracking Dataset..xlsx')

# Display the first 5 rows of the DataFrame
print(df.head())

"""## Initial Data Inspection



"""

print(f"DataFrame shape: {df.shape}")
print("\nDataFrame Info:")
df.info()
print("\nDescriptive Statistics:")
print(df.describe())

"""## Missing Value Analysis



"""

missing_values = df.isnull().sum()
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Count': missing_values,
    'Missing Percentage': missing_percentage
})

missing_df = missing_df[missing_df['Missing Count'] > 0].sort_values(by='Missing Percentage', ascending=False)

print("Missing Values Analysis:")
print(missing_df)

import matplotlib.pyplot as plt
import seaborn as sns

# Filter out columns with no missing values for plotting
missing_df_plot = missing_df[missing_df['Missing Percentage'] > 0]

plt.figure(figsize=(12, 7))
sns.barplot(x=missing_df_plot.index, y=missing_df_plot['Missing Percentage'], hue=missing_df_plot.index, palette='viridis', legend=False)
plt.title('Percentage of Missing Values Per Column', fontsize=16)
plt.xlabel('Columns', fontsize=12)
plt.ylabel('Missing Percentage (%)', fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(fontsize=10)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""## Categorical Variable Analysis

To analyze the distribution of the specified categorical variables, I will first calculate and print the value counts for 'Market/Regular', 'GpsProvider', and 'vehicleType' to see their frequency distributions. This will help in understanding the unique categories and their occurrences before plotting.
"""

print("Value counts for 'Market/Regular ':\n", df['Market/Regular '].value_counts())
print("\nValue counts for 'GpsProvider':\n", df['GpsProvider'].value_counts())
print("\nValue counts for 'vehicleType':\n", df['vehicleType'].value_counts())

# Get the order of vehicle types by their counts in descending order
vehicle_type_order = df['vehicleType'].value_counts().index

# Plotting categorical variables
plt.figure(figsize=(18, 6))

plt.subplot(1, 3, 1)
sns.countplot(data=df, x='Market/Regular ', hue='Market/Regular ', palette='viridis', legend=False)
plt.title('Distribution of Market/Regular')
plt.xlabel('Market/Regular')
plt.ylabel('Count')

plt.subplot(1, 3, 2)
sns.countplot(data=df, x='GpsProvider', hue='GpsProvider', palette='magma', legend=False)
plt.title('Distribution of GpsProvider')
plt.xlabel('GpsProvider')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')

plt.subplot(1, 3, 3)
sns.countplot(data=df, x='vehicleType', hue='vehicleType', palette='cividis', legend=False, order=vehicle_type_order)
plt.title('Distribution of vehicleType')
plt.xlabel('vehicleType')
plt.ylabel('Count')
plt.xticks(rotation=90, ha='right')

plt.tight_layout()
plt.show()

"""## Numerical Variable Analysis

To analyze the distribution and statistical properties of the specified numerical variables, I will create histograms to visualize their distributions and box plots to show their statistical properties (median, quartiles, outliers). I will arrange these plots in a figure using subplots for a clear comparison.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Select the numerical columns for analysis
numerical_cols = ['TRANSPORTATION_DISTANCE_IN_KM', 'Minimum_kms_to_be_covered_in_a_day']

plt.figure(figsize=(15, 12))

# Plot for 'TRANSPORTATION_DISTANCE_IN_KM'
plt.subplot(2, 2, 1)
sns.histplot(df['TRANSPORTATION_DISTANCE_IN_KM'].dropna(), kde=True, color='skyblue')
plt.title('Distribution of Transportation Distance (KM)')
plt.xlabel('Transportation Distance (KM)')
plt.ylabel('Frequency')

plt.subplot(2, 2, 2)
sns.boxplot(x=df['TRANSPORTATION_DISTANCE_IN_KM'].dropna(), color='lightcoral')
plt.title('Box Plot of Transportation Distance (KM)')
plt.xlabel('Transportation Distance (KM)')

# Plot for 'Minimum_kms_to_be_covered_in_a_day'
plt.subplot(2, 2, 3)
sns.histplot(df['Minimum_kms_to_be_covered_in_a_day'].dropna(), kde=True, color='lightgreen')
plt.title('Distribution of Minimum KMs to be Covered in a Day')
plt.xlabel('Minimum KMs to be Covered in a Day')
plt.ylabel('Frequency')

plt.subplot(2, 2, 4)
sns.boxplot(x=df['Minimum_kms_to_be_covered_in_a_day'].dropna(), color='lightgoldenrodyellow')
plt.title('Box Plot of Minimum KMs to be Covered in a Day')
plt.xlabel('Minimum KMs to be Covered in a Day')

plt.tight_layout()
plt.show()

"""# **Case: 1 for LP**

## Data Preparation for On-time Optimization
"""

import pandas as pd
import pulp

# Reload the original DataFrame 'df'
df = pd.read_excel('/content/Transportation and Logistics Tracking Dataset..xlsx')

# Recreate df_cleaneds
df_cleaned = df.dropna(subset=['TRANSPORTATION_DISTANCE_IN_KM', 'vehicleType']).copy()
df_cleaned.reset_index(drop=True, inplace=True)

# Create the new 'combined_ontime_status' column
# 1 if ontime == 'G', else 0 (covers delay == 'R' or NaN in both)
df_cleaned.loc[:, 'combined_ontime_status'] = df_cleaned['ontime'].apply(lambda x: 1 if x == 'G' else 0)

# 2. Calculate the historical on-time delivery probability for each unique 'GpsProvider' using 'combined_ontime_status'
on_time_score = df_cleaned.groupby('GpsProvider')['combined_ontime_status'].mean().dropna()

# 3. Print the first 5 rows of df_cleaned with 'GpsProvider', 'ontime', and 'combined_ontime_status' columns
print("First 5 rows of df_cleaned with 'ontime' and 'combined_ontime_status' columns:")
print(df_cleaned[['GpsProvider', 'ontime', 'combined_ontime_status']].head())

# 4. Print the resulting on_time_score Series
print("\nHistorical On-Time Delivery Probability (on_time_score) for each GpsProvider (using combined_ontime_status):")
print(on_time_score)

import pulp

# Get a list of unique 'GpsProvider' values from the updated on_time_score Series
gps_providers = on_time_score.index.tolist()

# Get trip indices from df_cleaned
trip_ids_ontime = df_cleaned.index.tolist()

# Initialize a PuLP problem object named model_ontime with the objective to maximize
model_ontime = pulp.LpProblem("On_Time_Optimization", pulp.LpMaximize)

# Create binary decision variables, y_ik
y = pulp.LpVariable.dicts(
    "Assign_GpsProvider", ((i, k) for i in trip_ids_ontime for k in gps_providers), cat='Binary'
)

# Formulate the objective function
# Maximize: Total Expected On-Time Score = sum_i (sum_k (y_ik * on_time_score[k]))
model_ontime += (
    pulp.lpSum(
        y[(i, k)] * on_time_score[k] for i in trip_ids_ontime for k in gps_providers
    ),
    "Total Expected On-Time Score"
)

# Add a constraint for each trip
# Each trip must be assigned exactly one GpsProvider
for i in trip_ids_ontime:
    model_ontime += (
        pulp.lpSum(y[(i, k)] for k in gps_providers) == 1,
        f"One_GpsProvider_Per_Trip_{i}"
    )

# Solve the PuLP model for on-time optimization
model_ontime.solve()

# Print the status of the solution
print("Status of On-Time Optimization (re-run):", pulp.LpStatus[model_ontime.status])

# Print the optimal total expected on-time score
optimal_on_time_score = pulp.value(model_ontime.objective)
print("Optimal Total Expected On-Time Score (re-run):", optimal_on_time_score)

# Store the assigned GpsProvider and its on-time score for each trip
assigned_gps_providers = []
assigned_on_time_scores = []

for i in trip_ids_ontime:
    assigned_provider = None
    on_time_for_trip = 0
    for k in gps_providers:
        if y[(i, k)].varValue == 1:
            assigned_provider = k
            on_time_for_trip = on_time_score[k]
            break
    assigned_gps_providers.append(assigned_provider)
    assigned_on_time_scores.append(on_time_for_trip)

# Update the columns in df_cleaned
df_cleaned['Assigned_GpsProvider'] = assigned_gps_providers
df_cleaned['Assigned_OnTime_Score'] = assigned_on_time_scores

# Display the first few rows with the new columns
print("\nDataFrame with assigned GpsProviders and their on-time scores (re-run, first 5 rows):")
print(df_cleaned[['GpsProvider', 'Assigned_GpsProvider', 'Assigned_OnTime_Score']].head())

"""## Present On-time Optimization Results



"""

print(f"Optimal Total Expected On-Time Score: {optimal_on_time_score:.2f}")

print("\nDistribution of Assigned GpsProviders:")
print(df_cleaned['Assigned_GpsProvider'].value_counts())

# Compare original GpsProvider with assigned GpsProvider
num_changed_assignments_ontime = (df_cleaned['GpsProvider'] != df_cleaned['Assigned_GpsProvider']).sum()
print(f"\nNumber of trips where assigned GpsProvider differs from original: {num_changed_assignments_ontime} out of {len(df_cleaned)}")
print(f"Percentage of changed assignments: {(num_changed_assignments_ontime / len(df_cleaned)) * 100:.2f}%")

"""# **case: 2 for LP**
Calculate `trip_cost` for each trip in `df_cleaned` using the provided `vehicle_costs_2025` and `default_cost` to create a `vehicle_cost_per_km` lookup. Then, formulate and solve a multi-objective linear programming model using PuLP to maximize the total expected on-time delivery score while minimizing the total trip cost, applying the calculated `trip_cost` for a realistic budget.

## Calculate Trip Costs Based on Provided Vehicle Costs

To calculate the trip costs, I will define the `vehicle_costs_2025` dictionary and a `default_cost`. Then, I will create a `vehicle_cost_per_km` column by mapping `vehicleType` to its corresponding cost, using the default cost for unlisted types. Finally, I will calculate the `trip_cost` by multiplying distance with `vehicle_cost_per_km` and display the updated DataFrame.

# **below vehicle costs are considered from real world logistic data information**
"""

import numpy as np

# Define the vehicle costs per km for 2025
vehicle_costs_2025 = {
    '32 FT Multi-Axle 14MT - HCV': 23.5,
    '32 FT Single-Axle 7MT - HCV': 20.5,
    '24 / 26 FT Taurus Open 2MT - HCV': 22.0,
    '32 FT Taurus Open 1GT-HCV - Trailer': 23.5,
    '19 FT XL Container 18MT': 22.5,
    '24 FT XL Body 18MT': 21.5,
    '20 FT Open 7MTV Mini-LCV': 17.5,
    '15 MT Single Axle (7-8.5) Container - HCV': 22.0,
    '26 FT Taurus Open - HCV': 22.0,
    '12 MT Closed (Lower Body)': 20.5,
    '17 FT Tata Ace (Closed Body)': 20.0,
    '22 FT Open Body 16MT': 21.5,
    '20 FT Open Bed Single Axle': 21.0,
    '40 FT Multi-Axle Trailer 35MT': 26.0,
    '40 FT Single Axle Trailer 20MT': 24.0,
    '20 FT SXL Container': 20.0,
    '24 FT SXL Container': 22.0,
    '19 FT OPEN BODY 8 MT': 19.0,
    '20 FT CLOSE 7MT-MCV': 18.0,
    'Tata 407 Open 2MT - Mini-LCV': 16.0,
    '25 FT Open Body 21MT': 22.0,
    '1.5 MT Pickup (Open Body)': 15.0,
    '15 FT Single-Axle 7.2MT (8.5 H) Container - HCV': 21.0,
    '26 FT Taurus Open 27MT - HCV': 23.0,
    '20 FT Open 9MT - MCV': 20.0,
    '22 FT Closed Container': 21.0,
    '30 FT Open SXL 30MT': 24.0,
    '1.5 MT Vehicle (Closed Body)': 15.5,
    '1 MT Tata Ace (Closed Body)': 14.0,
    '17 FT Open 5MT - MCV': 17.0,
    '17 FT Container': 19.0,
    '1 MT Tata Ace (Open Body)': 13.0,
    '27 FT Open Body 21MT': 22.5,
    '40 FT Flat Bed Single-Axle 20MT - Trailer': 24.5,
    '32 FT Closed Container 15 MT': 22.5,
    '20 FT Closed  Container 8MT': 18.5,
    '37 FT Trailer (Open)': 25.0,
    'Tata 407 / 14 FT Open 3MT LCV': 16.5,
    '30 FT Open MXL 30MT': 24.5,
    '31 FT Open Body 18MT': 21.0,
    '32 FT Open Tarus': 23.0,
    '14 FT Open - 3 MT': 14.5,
    '19 FT SXL Container': 20.5,
    'Mahindra LCV 1MT': 13.5,
    '24 / 26 FT  Closed Container  20MT - HCV': 22.5,
    '25 FT Closed Body 20MT': 21.5,
    '50 FT Flat Bed 30MT - Trailer': 27.0,
    '40 FT 3XL Trailer 35MT': 25.0,
    '40 FT Flat Bed Multi-Axle 27MT - Trailer': 26.5,
    '28 FT Open Body 25MT': 22.0,
    '24 | 26 FT Taurus Open 21MT - HCV': 22.5,
    '40 FT Flat Bed Double-Axle 21MT - Trailer': 25.5,
    '22 FT Taurus Open 16MT - HCV': 21.0
}

default_cost = 21.5  # A reasonable average for unlisted vehicle types

# Create 'vehicle_cost_per_km' column using .loc to avoid SettingWithCopyWarning
df_cleaned.loc[:, 'vehicle_cost_per_km'] = df_cleaned['vehicleType'].map(vehicle_costs_2025).fillna(default_cost)

# Calculate 'trip_cost' using .loc
df_cleaned.loc[:, 'trip_cost'] = df_cleaned['TRANSPORTATION_DISTANCE_IN_KM'] * df_cleaned['vehicle_cost_per_km']

# Display the first few rows with the new columns
print("First 5 rows of df_cleaned with new cost columns:")
print(df_cleaned[['vehicleType', 'TRANSPORTATION_DISTANCE_IN_KM', 'vehicle_cost_per_km', 'trip_cost']].head())

"""## Formulate Multi-Objective LP Model (On-Time & Cost)

To formulate the multi-objective linear programming model, I will define the trip IDs and GPS providers, calculate the total trip cost and budget, initialize the PuLP problem, create binary decision variables for assignments, and then formulate the combined objective function and add the necessary constraints for unique provider assignment per trip and overall budget.
"""

import pulp

# 1. Get the list of trip IDs
trip_ids_multi = df_cleaned.index.tolist()

# 2. Get the list of unique GPS providers
gps_providers_multi = on_time_score.index.tolist()

# 3. Calculate the total sum of trip costs from df_cleaned
total_sum_trip_cost = df_cleaned['trip_cost'].sum()

# 4. Define a total budget (5% flexibility)
total_budget = total_sum_trip_cost * 1.05

# 5. Initialize a PuLP problem with the objective to minimize
model_multi = pulp.LpProblem("Multi_Objective_GPS_Assignment_Cost_OnTime", pulp.LpMinimize)

# 6. Create binary decision variables
x = pulp.LpVariable.dicts(
    "Assign_GpsProvider_Multi",
    ((i, k) for i in trip_ids_multi for k in gps_providers_multi),
    cat='Binary'
)

# Define cost and on-time score expressions
total_trip_cost_expression = pulp.lpSum(
    x[(i, k)] * df_cleaned['trip_cost'].loc[i]
    for i in trip_ids_multi
    for k in gps_providers_multi
)

total_expected_ontime_score_expression = pulp.lpSum(
    x[(i, k)] * on_time_score[k]
    for i in trip_ids_multi
    for k in gps_providers_multi
)

# 7. Formulate the combined objective function
# Objective: Minimize (0.7 * total_trip_cost) - (0.3 * total_expected_ontime_score)
model_multi += (0.7 * total_trip_cost_expression) - (0.3 * total_expected_ontime_score_expression), \
               "Combined_Objective_Cost_OnTime"

# 8. Add constraint for each trip: Each trip must be assigned exactly one GpsProvider
for i in trip_ids_multi:
    model_multi += (
        pulp.lpSum(x[(i, k)] for k in gps_providers_multi) == 1,
        f"One_GpsProvider_Per_Trip_Multi_{i}"
    )

# 9. Add a budget constraint
model_multi += (total_trip_cost_expression <= total_budget, "Total_Cost_Budget_Constraint")

print("Successfully formulated the multi-objective LP problem.")
print(f"Number of trips: {len(trip_ids_multi)}")
print(f"Number of unique GpsProviders: {len(gps_providers_multi)}")
print(f"Total sum of trip costs: {total_sum_trip_cost:.2f}")
print(f"Total budget: {total_budget:.2f}")

"""
The multi-objective linear programming model for maximizing on-time delivery and minimizing cost has been formulated. The next step is to solve this model using PuLP to find the optimal assignments and then extract the total on-time score, total cost, and assigned GPS providers.

"""

import pulp

# Solve the PuLP model for multi-objective optimization
model_multi.solve()

# Print the status of the solution
print("Status of Multi-Objective Optimization:", pulp.LpStatus[model_multi.status])

# Extract and print the optimal total combined objective value
optimal_combined_objective = pulp.value(model_multi.objective)
print("Optimal Combined Objective Value (0.7*Cost - 0.3*OnTimeScore):", optimal_combined_objective)

# Calculate the total trip cost and total expected on-time score from the optimal solution
total_optimal_cost = 0
total_optimal_ontime_score = 0
assigned_gps_providers_multi = []
assigned_on_time_scores_multi = []
assigned_costs_multi = []

for i in trip_ids_multi:
    assigned_provider = "No Optimal Assignment"
    on_time_for_trip = 0
    cost_for_trip = 0
    for k in gps_providers_multi:
        if x[(i, k)].varValue == 1:
            assigned_provider = k
            on_time_for_trip = on_time_score[k]
            cost_for_trip = df_cleaned['trip_cost'].loc[i]
            break
    assigned_gps_providers_multi.append(assigned_provider)
    assigned_on_time_scores_multi.append(on_time_for_trip)
    assigned_costs_multi.append(cost_for_trip)

# Add the new columns to df_cleaned for multi-objective results
df_cleaned['Assigned_GpsProvider_Multi'] = assigned_gps_providers_multi
df_cleaned['Assigned_OnTime_Score_Multi'] = assigned_on_time_scores_multi
df_cleaned['Assigned_Cost_Multi'] = assigned_costs_multi

total_optimal_cost = df_cleaned['Assigned_Cost_Multi'].sum()
total_optimal_ontime_score = df_cleaned['Assigned_OnTime_Score_Multi'].sum()

print(f"\nOptimal Total Trip Cost: {total_optimal_cost:.2f}")
print(f"Optimal Total Expected On-Time Score: {total_optimal_ontime_score:.2f}")

# Display the first few rows with the new columns
print("\nDataFrame with multi-objective assigned GpsProviders and scores (first 5 rows):")
print(df_cleaned[['GpsProvider', 'Assigned_GpsProvider_Multi', 'Assigned_OnTime_Score_Multi', 'Assigned_Cost_Multi']].head())

"""## Present Multi-Objective Optimization Results



"""

print(f"Optimal Total Expected On-Time Score (Multi-Objective): {total_optimal_ontime_score:.2f}")
print(f"Optimal Total Trip Cost (Multi-Objective): {total_optimal_cost:.2f}")

"""
To continue interpreting the multi-objective optimization results, I will now display the value counts for the 'Assigned_GpsProvider_Multi' column, and then calculate and print the differences between the multi-objective assignments and both the original and single-objective assignments.

"""

print("\nDistribution of Assigned GpsProviders (Multi-Objective):")
print(df_cleaned['Assigned_GpsProvider_Multi'].value_counts())

# Compare Assigned_GpsProvider_Multi with original GpsProvider
num_changed_assignments_multi_vs_original = (df_cleaned['GpsProvider'] != df_cleaned['Assigned_GpsProvider_Multi']).sum()
print(f"\nNumber of trips where multi-objective assigned GpsProvider differs from original: {num_changed_assignments_multi_vs_original} out of {len(df_cleaned)}")
print(f"Percentage of changed assignments (multi-objective vs. original): {(num_changed_assignments_multi_vs_original / len(df_cleaned)) * 100:.2f}%")

# Compare Assigned_GpsProvider_Multi with Assigned_GpsProvider (single-objective)
num_changed_assignments_multi_vs_single = (df_cleaned['Assigned_GpsProvider'] != df_cleaned['Assigned_GpsProvider_Multi']).sum()
print(f"\nNumber of trips where multi-objective assigned GpsProvider differs from single-objective: {num_changed_assignments_multi_vs_single} out of {len(df_cleaned)}")
print(f"Percentage of changed assignments (multi-objective vs. single-objective): {(num_changed_assignments_multi_vs_single / len(df_cleaned)) * 100:.2f}%")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(20, 7))

# Plot for Assigned GpsProviders (Multi-Objective)
plt.subplot(1, 3, 1)
sns.countplot(data=df_cleaned, x='Assigned_GpsProvider_Multi', hue='Assigned_GpsProvider_Multi', palette='viridis', legend=False)
plt.title('Distribution of Multi-Objective Assigned GpsProviders')
plt.xlabel('GpsProvider')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')

# Plot for Assigned GpsProviders (Single-Objective)
plt.subplot(1, 3, 2)
sns.countplot(data=df_cleaned, x='Assigned_GpsProvider', hue='Assigned_GpsProvider', palette='magma', legend=False)
plt.title('Distribution of Single-Objective Assigned GpsProviders')
plt.xlabel('GpsProvider')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')

# Plot for Original GpsProviders
plt.subplot(1, 3, 3)
sns.countplot(data=df_cleaned, x='GpsProvider', hue='GpsProvider', palette='cividis', legend=False, order=df_cleaned['GpsProvider'].value_counts().index)
plt.title('Distribution of Original GpsProviders')
plt.xlabel('GpsProvider')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

"""# **case 3: for LP**

## Define GpsProvider - VehicleType Compatibility Matrix

To begin generating the compatibility matrix, I will extract all unique `GpsProvider`s and `vehicleType`s from the `df_cleaned` DataFrame. This will provide the basic sets for creating the matrix
"""

unique_providers = df_cleaned['GpsProvider'].dropna().unique().tolist()
unique_vehicle_types = df_cleaned['vehicleType'].dropna().unique().tolist()

print("Unique GpsProviders (first 5):")
print(unique_providers[:5])
print("\nUnique Vehicle Types (first 5):")
print(unique_vehicle_types[:5])

"""
To categorize each `vehicleType` as 'Small', 'Medium', or 'Large', I will define a function that checks for keywords in the vehicle type names and apply it to create a new `vehicle_category` column in `df_cleaned` and also store this mapping in a dictionary.

"""

def categorize_vehicle_type(vehicle_type):
    vehicle_type_lower = str(vehicle_type).lower()
    if 'mini-lcv' in vehicle_type_lower or 'tata ace' in vehicle_type_lower or '1 mt' in vehicle_type_lower or '1.5 mt' in vehicle_type_lower or 'mahine lcv' in vehicle_type_lower or 'small' in vehicle_type_lower or 'micro' in vehicle_type_lower:
        return 'Small'
    elif 'lcv' in vehicle_type_lower or 'mcv' in vehicle_type_lower or 'light' in vehicle_type_lower or 'medium' in vehicle_type_lower or '19 ft' in vehicle_type_lower or '20 ft' in vehicle_type_lower or '22 ft' in vehicle_type_lower or '24 ft' in vehicle_type_lower:
        return 'Medium'
    elif 'hcv' in vehicle_type_lower or 'trailer' in vehicle_type_lower or 'multi-axle' in vehicle_type_lower or 'large' in vehicle_type_lower or 'heavy' in vehicle_type_lower or '32 ft' in vehicle_type_lower or '40 ft' in vehicle_type_lower or '50 ft' in vehicle_type_lower:
        return 'Large'
    return 'Medium' # Default to Medium if no clear category is found

# Create a new column for vehicle category
df_cleaned.loc[:, 'vehicle_category'] = df_cleaned['vehicleType'].apply(categorize_vehicle_type)

# Create a dictionary mapping each unique vehicleType to its category
vehicle_type_category_map = df_cleaned.set_index('vehicleType')['vehicle_category'].to_dict()

print("First 5 rows with 'vehicle_category' column:")
print(df_cleaned[['vehicleType', 'vehicle_category']].head())

print("\nExample vehicle type categories from map (first 5 unique):")
# Get first 5 unique keys from the map for display
example_keys = list(vehicle_type_category_map.keys())[:5]
for key in example_keys:
    print(f"{key}: {vehicle_type_category_map[key]}")

"""
Now that unique providers and vehicle type categories are defined, I will create a hypothetical `compatibility_matrix` dictionary. This matrix will map `GpsProvider`s to lists of `vehicleType`s they are compatible with, based on the logical rules for 'generalists', 'small vehicle specialists', and 'large vehicle specialists'. Finally, I will print the first few entries of this matrix to verify its structure.

"""

compatibility_matrix = {}

# Group providers into categories for hypothetical compatibility
generalists = ['CONSENT TRACK', 'VAMOSYS', 'JTECH', 'EKTA'] # Can handle all types
small_specialists = ['KRC LOGISTICS', 'MANUAL', 'NIMBLE', 'INSTANT'] # Small and Medium
large_specialists = ['WABCOTRANS', 'FORIGOTRANS', 'BALLY LOGISTICS', 'FLEETX'] # Medium and Large

# Ensure all providers in unique_providers are covered by a category, default to generalist if not specified
# Collect all categorized providers
categorized_providers = set(generalists + small_specialists + large_specialists)

# Add any remaining unique_providers to generalists if not already categorized
for provider in unique_providers:
    if provider not in categorized_providers:
        generalists.append(provider)
        categorized_providers.add(provider)

# Assign compatibility based on rules
for provider in unique_providers:
    if provider in generalists:
        compatibility_matrix[provider] = unique_vehicle_types
    elif provider in small_specialists:
        compatible_types = [vt for vt in unique_vehicle_types if vehicle_type_category_map.get(vt) in ['Small', 'Medium']]
        compatibility_matrix[provider] = compatible_types
    elif provider in large_specialists:
        compatible_types = [vt for vt in unique_vehicle_types if vehicle_type_category_map.get(vt) in ['Medium', 'Large']]
        compatibility_matrix[provider] = compatible_types
    else:
        # Default for any provider not explicitly listed in the categories (should be rare if logic is complete)
        compatibility_matrix[provider] = unique_vehicle_types # Default to generalist


print("First 3 entries of the generated compatibility matrix:")
# Print a few entries to verify
for i, (provider, compatible_vts) in enumerate(compatibility_matrix.items()):
    if i >= 3:
        break
    print(f"{provider}: {len(compatible_vts)} compatible vehicle types")
    print(f"  Examples: {compatible_vts[:2]}...") # Show first 2 compatible types for brevity

"""## Formulate Multi-Objective LP Model (On-Time & Cost with Compatibility)

To formulate the multi-objective linear programming model with compatibility constraints, I will follow the instructions to initialize the PuLP problem, define decision variables, set up the objective function, and add constraints for unique assignments, budget, and GpsProvider-vehicleType compatibility.
"""

import pulp

# 1. Initialize a PuLP problem object named model_multi_compat with the objective to minimize
model_multi_compat = pulp.LpProblem("Multi_Objective_GPS_Assignment_Compat", pulp.LpMinimize)

# 2. Define binary decision variables, x_compat
x_compat = pulp.LpVariable.dicts(
    "Assign_GpsProvider_Compat",
    ((i, k) for i in trip_ids_multi for k in gps_providers_multi),
    cat='Binary'
)

# Define cost and on-time score expressions for the new model
total_trip_cost_expression_compat = pulp.lpSum(
    x_compat[(i, k)] * df_cleaned['trip_cost'].loc[i]
    for i in trip_ids_multi
    for k in gps_providers_multi
)

total_expected_ontime_score_expression_compat = pulp.lpSum(
    x_compat[(i, k)] * on_time_score[k]
    for i in trip_ids_multi
    for k in gps_providers_multi
)

# 3. Formulate the combined objective function
# Objective: Minimize (0.7 * total_trip_cost) - (0.3 * total_expected_ontime_score)
model_multi_compat += (0.7 * total_trip_cost_expression_compat) - (0.3 * total_expected_ontime_score_expression_compat), \
               "Combined_Objective_Cost_OnTime_Compat"

# 4. Add a constraint for each trip: Each trip must be assigned exactly one GpsProvider
for i in trip_ids_multi:
    model_multi_compat += (
        pulp.lpSum(x_compat[(i, k)] for k in gps_providers_multi) == 1,
        f"One_GpsProvider_Per_Trip_Compat_{i}"
    )

# 5. Add a budget constraint
model_multi_compat += (total_trip_cost_expression_compat <= total_budget, "Total_Cost_Budget_Constraint_Compat")

# 6. Add the compatibility constraint
for i in trip_ids_multi:
    vehicle_type_for_trip = df_cleaned['vehicleType'].loc[i]
    for k in gps_providers_multi:
        if vehicle_type_for_trip not in compatibility_matrix.get(k, []):
            model_multi_compat += (x_compat[(i, k)] == 0, f"Compatibility_Constraint_{i}_{k}")

# 7. Print confirmation messages
print("Successfully formulated the multi-objective LP problem with compatibility.")
print(f"Number of trips: {len(trip_ids_multi)}")
print(f"Number of unique GpsProviders: {len(gps_providers_multi)}")
print(f"Total sum of trip costs: {total_sum_trip_cost:.2f}")
print(f"Total budget: {total_budget:.2f}")

import pulp

# Solve the PuLP model for multi-objective optimization with compatibility
model_multi_compat.solve()

# Print the status of the solution
print("Status of Multi-Objective Optimization with Compatibility:", pulp.LpStatus[model_multi_compat.status])

# Extract and print the optimal total combined objective value
optimal_combined_objective_compat = pulp.value(model_multi_compat.objective)
print("Optimal Combined Objective Value (0.7*Cost - 0.3*OnTimeScore) with Compatibility:", optimal_combined_objective_compat)

# Calculate the total trip cost and total expected on-time score from the optimal solution
total_optimal_cost_compat = 0
total_optimal_ontime_score_compat = 0
assigned_gps_providers_compat = []
assigned_on_time_scores_compat = []
assigned_costs_compat = []

for i in trip_ids_multi:
    assigned_provider = "No Optimal Assignment"
    on_time_for_trip = 0
    cost_for_trip = 0
    for k in gps_providers_multi:
        if x_compat[(i, k)].varValue == 1:
            assigned_provider = k
            on_time_for_trip = on_time_score[k]
            cost_for_trip = df_cleaned['trip_cost'].loc[i]
            break
    assigned_gps_providers_compat.append(assigned_provider)
    assigned_on_time_scores_compat.append(on_time_for_trip)
    assigned_costs_compat.append(cost_for_trip)

# Add the new columns to df_cleaned for multi-objective results with compatibility
df_cleaned['Assigned_GpsProvider_Compat'] = assigned_gps_providers_compat
df_cleaned['Assigned_OnTime_Score_Compat'] = assigned_on_time_scores_compat
df_cleaned['Assigned_Cost_Compat'] = assigned_costs_compat

total_optimal_cost_compat = df_cleaned['Assigned_Cost_Compat'].sum()
total_optimal_ontime_score_compat = df_cleaned['Assigned_OnTime_Score_Compat'].sum()

print(f"\nOptimal Total Trip Cost with Compatibility: {total_optimal_cost_compat:.2f}")
print(f"Optimal Total Expected On-Time Score with Compatibility: {total_optimal_ontime_score_compat:.2f}")

# Display the first few rows with the new columns
print("\nDataFrame with multi-objective assigned GpsProviders and scores (with compatibility, first 5 rows):")
print(df_cleaned[['GpsProvider', 'Assigned_GpsProvider_Multi', 'Assigned_OnTime_Score_Multi', 'Assigned_Cost_Multi', 'Assigned_GpsProvider_Compat', 'Assigned_OnTime_Score_Compat', 'Assigned_Cost_Compat']].head())

print(f"Optimal Total Expected On-Time Score (Multi-Objective with Compatibility): {total_optimal_ontime_score_compat:.2f}")
print(f"Optimal Total Trip Cost (Multi-Objective with Compatibility): {total_optimal_cost_compat:.2f}")

print("\nDistribution of Assigned GpsProviders (Multi-Objective with Compatibility):")
print(df_cleaned['Assigned_GpsProvider_Compat'].value_counts())

# Compare Assigned_GpsProvider_Compat with original GpsProvider
num_changed_assignments_compat_vs_original = (df_cleaned['GpsProvider'] != df_cleaned['Assigned_GpsProvider_Compat']).sum()
print(f"\nNumber of trips where multi-objective with compatibility assigned GpsProvider differs from original: {num_changed_assignments_compat_vs_original} out of {len(df_cleaned)}")
print(f"Percentage of changed assignments (multi-objective with compatibility vs. original): {(num_changed_assignments_compat_vs_original / len(df_cleaned)) * 100:.2f}%")

# Compare Assigned_GpsProvider_Compat with Assigned_GpsProvider (single-objective)
num_changed_assignments_compat_vs_single = (df_cleaned['Assigned_GpsProvider'] != df_cleaned['Assigned_GpsProvider_Compat']).sum()
print(f"\nNumber of trips where multi-objective with compatibility assigned GpsProvider differs from single-objective: {num_changed_assignments_compat_vs_single} out of {len(df_cleaned)}")
print(f"Percentage of changed assignments (multi-objective with compatibility vs. single-objective): {(num_changed_assignments_compat_vs_single / len(df_cleaned)) * 100:.2f}%")

# Compare Assigned_GpsProvider_Compat with Assigned_GpsProvider_Multi (multi-objective without compatibility)
num_changed_assignments_compat_vs_multi = (df_cleaned['Assigned_GpsProvider_Multi'] != df_cleaned['Assigned_GpsProvider_Compat']).sum()
print(f"\nNumber of trips where multi-objective with compatibility assigned GpsProvider differs from multi-objective without compatibility: {num_changed_assignments_compat_vs_multi} out of {len(df_cleaned)}")
print(f"Percentage of changed assignments (multi-objective with compatibility vs. multi-objective without compatibility): {(num_changed_assignments_compat_vs_multi / len(df_cleaned)) * 100:.2f}%")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(20, 7))

# Plot for Assigned GpsProviders (Multi-Objective with Compatibility)
plt.subplot(1, 3, 1)
sns.countplot(data=df_cleaned, x='Assigned_GpsProvider_Compat', hue='Assigned_GpsProvider_Compat', palette='viridis', legend=False)
plt.title('Distribution of Multi-Objective Assigned GpsProviders (with Compatibility)')
plt.xlabel('GpsProvider')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')

# Plot for Assigned GpsProviders (Multi-Objective without Compatibility)
plt.subplot(1, 3, 2)
sns.countplot(data=df_cleaned, x='Assigned_GpsProvider_Multi', hue='Assigned_GpsProvider_Multi', palette='magma', legend=False)
plt.title('Distribution of Multi-Objective Assigned GpsProviders (without Compatibility)')
plt.xlabel('GpsProvider')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')

# Plot for Original GpsProviders
plt.subplot(1, 3, 3)
sns.countplot(data=df_cleaned, x='GpsProvider', hue='GpsProvider', palette='cividis', legend=False, order=df_cleaned['GpsProvider'].value_counts().index)
plt.title('Distribution of Original GpsProviders')
plt.xlabel('GpsProvider')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

"""## Calculate Baseline Cost

To calculate the baseline total cost and on-time score, I will sum the 'trip_cost' column for the cost and for the on-time score, I will map the original 'GpsProvider' to its 'on_time_score' and sum these values, then print both results.
"""

import numpy as np

# 1. Calculate the sum of the 'trip_cost' column in the df_cleaned DataFrame
baseline_total_cost = df_cleaned['trip_cost'].sum()

# 2. Calculate the sum of the 'Assigned_OnTime_Score_Compat' column in the df_cleaned DataFrame
#    when considering the original GpsProvider. This will be the baseline total expected on-time score.
#    We need to map the original GpsProvider to its on_time_score from the 'on_time_score' Series.

baseline_total_ontime_score = df_cleaned['GpsProvider'].map(on_time_score).sum()

# 3. Print both the baseline_total_cost and baseline_total_ontime_score
print(f"Baseline Total Trip Cost (Original GpsProviders): {baseline_total_cost:.2f}")
print(f"Baseline Total Expected On-Time Score (Original GpsProviders): {baseline_total_ontime_score:.2f}")

results = {
    'Baseline (Original Assignments)': {
        'Cost': baseline_total_cost,
        'On-Time Score': baseline_total_ontime_score
    },
    'Single-Objective (On-Time Max)': {
        'Cost': total_optimal_cost,  # This was the cost for the single objective model (which was not optimized for cost)
        'On-Time Score': optimal_on_time_score
    },
    'Multi-Objective (On-Time & Cost)': {
        'Cost': total_optimal_cost,
        'On-Time Score': total_optimal_ontime_score
    },
    'Multi-Objective (On-Time & Cost with Compatibility)': {
        'Cost': total_optimal_cost_compat,
        'On-Time Score': total_optimal_ontime_score_compat
    }
}

print("Comparison of Total Trip Cost and Expected On-Time Score Across Models:")
for model, values in results.items():
    print(f"\n{model}:")
    print(f"  Total Trip Cost: {values['Cost']:.2f}")
    print(f"  Total Expected On-Time Score: {values['On-Time Score']:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Prepare data for plotting
plot_data = pd.DataFrame.from_dict(results, orient='index')
plot_data.index.name = 'Model'

plt.figure(figsize=(15, 6))

# Bar chart for Total Trip Cost
plt.subplot(1, 2, 1)
sns.barplot(x=plot_data.index, y='Cost', data=plot_data, palette='viridis')
plt.title('Comparison of Total Trip Cost Across Models')
plt.xlabel('Model')
plt.ylabel('Total Trip Cost (₹)')
plt.xticks(rotation=45, ha='right')
plt.ticklabel_format(style='plain', axis='y') # Prevent scientific notation

# Bar chart for Total Expected On-Time Score
plt.subplot(1, 2, 2)
sns.barplot(x=plot_data.index, y='On-Time Score', data=plot_data, palette='plasma')
plt.title('Comparison of Total Expected On-Time Score Across Models')
plt.xlabel('Model')
plt.ylabel('Total Expected On-Time Score')
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

"""## Generate Provider Performance Ranking Bar Graph

To visualize the `on_time_score` for each `GpsProvider` as requested, I need to sort the `on_time_score` Series in descending order and then create a bar plot using seaborn to display this ranking with appropriate labels and title.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# 1. Sort the on_time_score Series in descending order
on_time_score_sorted = on_time_score.sort_values(ascending=False)

# 2. Create a bar plot
plt.figure(figsize=(14, 7))
sns.barplot(x=on_time_score_sorted.index, y=on_time_score_sorted.values, hue=on_time_score_sorted.index, palette='viridis', legend=False)

# 3. Set the title of the plot
plt.title('GpsProvider On-Time Performance Ranking', fontsize=16)

# 4. Label the x-axis and y-axis
plt.xlabel('GpsProvider', fontsize=12)
plt.ylabel('On-Time Score', fontsize=12)

# 5. Rotate the x-axis labels for better readability
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(fontsize=10)

# Add grid for better readability
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
# 6. Display the plot
plt.show()

"""## Visualize Provider Assignment Distributions

To compare the distribution of GpsProvider assignments across different models as requested, I will create a 2x2 grid of count plots using seaborn to visualize the assignments from the original data, single-objective, multi-objective (without compatibility), and multi-objective (with compatibility) models.
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(20, 15))

# 1. Original GpsProviders
plt.subplot(2, 2, 1)
sns.countplot(data=df_cleaned, x='GpsProvider', hue='GpsProvider', palette='viridis', legend=False, order=df_cleaned['GpsProvider'].value_counts().index)
plt.title('Distribution of Original GpsProviders', fontsize=14)
plt.xlabel('GpsProvider', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=10)

# 2. Single-Objective Assigned GpsProviders
plt.subplot(2, 2, 2)
sns.countplot(data=df_cleaned, x='Assigned_GpsProvider', hue='Assigned_GpsProvider', palette='magma', legend=False)
plt.title('Distribution of Single-Objective Assigned GpsProviders', fontsize=14)
plt.xlabel('GpsProvider', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=10)

# 3. Multi-Objective (without Compatibility) Assigned GpsProviders
plt.subplot(2, 2, 3)
sns.countplot(data=df_cleaned, x='Assigned_GpsProvider_Multi', hue='Assigned_GpsProvider_Multi', palette='cividis', legend=False)
plt.title('Distribution of Multi-Objective (without Compatibility) Assigned GpsProviders', fontsize=14)
plt.xlabel('GpsProvider', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=10)

# 4. Multi-Objective (with Compatibility) Assigned GpsProviders
plt.subplot(2, 2, 4)
sns.countplot(data=df_cleaned, x='Assigned_GpsProvider_Compat', hue='Assigned_GpsProvider_Compat', palette='plasma', legend=False)
plt.title('Distribution of Multi-Objective (with Compatibility) Assigned GpsProviders', fontsize=14)
plt.xlabel('GpsProvider', fontsize=12)
plt.ylabel('Count', fontsize=12)
plt.xticks(rotation=45, ha='right', fontsize=10)

plt.tight_layout()
plt.show()